export type TableItem = {
  src: string;
  alt: string;
  top: number;
  left: number;
  width: number;
  rotate: number;
  z: number;
  shadow?: boolean;
};

export const deckA: TableItem[] = [
  {
    src: "/table-scene/photo-1.png",
    alt: "Fashion portrait with floral shirt",
    top: -8,
    left: 8,
    width: 17,
    rotate: -8,
    z: 3,
  },
  {
    src: "/table-scene/photo-2.png",
    alt: "Street style in front of blue door",
    top: 2,
    left: 28,
    width: 19,
    rotate: 6,
    z: 4,
  },
  {
    src: "/table-scene/photo-3.png",
    alt: "Upcycled clothing flat lay",
    top: -6,
    left: 47,
    width: 18,
    rotate: 12,
    z: 2,
  },
  {
    src: "/table-scene/paper-1.png",
    alt: "Research paper on sustainable fashion",
    top: 10,
    left: 66,
    width: 20,
    rotate: 9,
    z: 5,
  },
  {
    src: "/table-scene/photo-1.png",
    alt: "Fashion portrait",
    top: -10,
    left: 84,
    width: 14,
    rotate: -14,
    z: 2,
  },
  {
    src: "/table-scene/photo-4.png",
    alt: "Garments magazine cover",
    top: 48,
    left: 1,
    width: 16,
    rotate: -3,
    z: 4,
  },
  {
    src: "/table-scene/photo-6.png",
    alt: "Colorful sneakers street photo",
    top: 62,
    left: 32,
    width: 17,
    rotate: -10,
    z: 3,
  },
  {
    src: "/table-scene/film-1.png",
    alt: "Film strip with streetwear frames",
    top: 50,
    left: 47,
    width: 12,
    rotate: 18,
    z: 5,
  },
  {
    src: "/table-scene/photo-5.png",
    alt: "Streetwear upcycling zine",
    top: 56,
    left: 76,
    width: 18,
    rotate: 7,
    z: 3,
  },
  {
    src: "/table-scene/film-1.png",
    alt: "Film strip",
    top: 30,
    left: 90,
    width: 11,
    rotate: -20,
    z: 2,
  },
];

export const deckB: TableItem[] = [
  {
    src: "/table-scene/photo-5.png",
    alt: "Streetwear zine cover",
    top: -6,
    left: 12,
    width: 18,
    rotate: 10,
    z: 3,
  },
  {
    src: "/table-scene/photo-6.png",
    alt: "Chunky sneakers close up",
    top: 4,
    left: 40,
    width: 18,
    rotate: -7,
    z: 4,
  },
  {
    src: "/table-scene/photo-4.png",
    alt: "Garments magazine",
    top: -8,
    left: 66,
    width: 16,
    rotate: 8,
    z: 3,
  },
  {
    src: "/table-scene/paper-1.png",
    alt: "Sustainable fashion paper",
    top: 44,
    left: 6,
    width: 20,
    rotate: -6,
    z: 5,
  },
  {
    src: "/table-scene/photo-3.png",
    alt: "Clothing moodboard flat lay",
    top: 58,
    left: 38,
    width: 18,
    rotate: 5,
    z: 4,
  },
  {
    src: "/table-scene/photo-2.png",
    alt: "Street style photo",
    top: 46,
    left: 60,
    width: 17,
    rotate: -12,
    z: 3,
  },
  {
    src: "/table-scene/photo-1.png",
    alt: "Colorful fashion portrait",
    top: 52,
    left: 82,
    width: 15,
    rotate: 14,
    z: 4,
  },
  {
    src: "/table-scene/film-1.png",
    alt: "Photographic film strip",
    top: 18,
    left: 88,
    width: 11,
    rotate: 22,
    z: 5,
  },
];

export const deckC: TableItem[] = [
  {
    src: "/table-scene/photo-2.png",
    alt: "Street style photo",
    top: -4,
    left: 10,
    width: 17,
    rotate: -9,
    z: 3,
  },
  {
    src: "/table-scene/photo-4.png",
    alt: "Garments magazine cover",
    top: 6,
    left: 34,
    width: 18,
    rotate: 11,
    z: 4,
  },
  {
    src: "/table-scene/film-1.png",
    alt: "Film strip",
    top: -10,
    left: 58,
    width: 12,
    rotate: -16,
    z: 2,
  },
  {
    src: "/table-scene/photo-6.png",
    alt: "Sneakers street photo",
    top: 8,
    left: 74,
    width: 16,
    rotate: 7,
    z: 5,
  },
  {
    src: "/table-scene/paper-1.png",
    alt: "Research paper",
    top: 46,
    left: 4,
    width: 19,
    rotate: -5,
    z: 4,
  },
  {
    src: "/table-scene/photo-1.png",
    alt: "Fashion portrait",
    top: 54,
    left: 30,
    width: 17,
    rotate: 13,
    z: 3,
  },
  {
    src: "/table-scene/photo-5.png",
    alt: "Streetwear zine",
    top: 50,
    left: 55,
    width: 18,
    rotate: -11,
    z: 5,
  },
  {
    src: "/table-scene/photo-3.png",
    alt: "Clothing flat lay",
    top: 60,
    left: 80,
    width: 15,
    rotate: 18,
    z: 3,
  },
];
